controller_manager:
    ros__parameters:
        update_rate: 1000  # Hz

        use_sim_time: true

        position_controller:
            type: position_controllers/JointGroupPositionController

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        velocity_controller:
            type: velocity_controllers/JointGroupVelocityController



position_controller:
    ros__parameters:
        joints:
            - steering_joint_1
            - steering_joint_2
            - link_joint_1
            - joint_link_2
            - joint_link_3
            - joint_link_4
            - joint_link_5
            - end_effector_joint

        interface_name: position
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity


velocity_controller:
    ros__parameters:
        joints:
            - wheel_joint_1
            - wheel_joint_2
            - wheel_joint_3
            - wheel_joint_
            
        interface_name: velocity
        command_interfaces:
            - velocity
        state_interfaces:
            - position
            - velocity
                     